### ISSUE TITLE
FanOutFanIn<T>(...) fails on empty collection

### ISSUE THREAD

**Issue by thomaseyde** [Appstream-Studio/durable-patterns#21]
I run the following code where activity `ReadCustomer` returns an empty collection.:

```
var options = new FanOutFanInOptions(1, 50);
await patterns.WithContext(context)
              .RunActivity<ReadCustomers>()
              .FanOutFanIn<ReadInventoryFiles>(options)
              .FanOutFanIn<RemoveOldFiles>(options)
              .FanOutFanIn<RemoveProcessedFiles>(options)
              .FanOutFanIn<CreateTargetCsvFile>(options)
              .FanOutFanIn<AppendFileToCsv>(options)
              .FanOutFanIn<AppendFileToIndex>(options)
              .ExecuteAsync();
``` 

Durable Patterns fail with:
```
Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average[TSource,TSelector,TAccumulator,TResult](IEnumerable`1 source, Func`2 selector)
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at AppStream.DurablePatterns.Executor.StepExecutor.FanOutFanInStep.FanOutFanInStepExecutor.ExecuteFanOutFanInInternalAsync[TInputCollection,TInputItem,TResultCollection,TResultItem](Step step, TaskOrchestrationContext context, TInputCollection input)
   at AppStream.DurablePatterns.Executor.StepExecutor.FanOutFanInStep.FanOutFanInStepExecutor.ExecuteStepInternalAsync(Step step, TaskOrchestrationContext context, Object input)
   at AppStream.DurablePatterns.Executor.DurablePatternsExecutor.ExecuteAsync(IEnumerable`1 steps, TaskOrchestrationContext context)
Stack:    at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Average[TSource,TSelector,TAccumulator,TResult](IEnumerable`1 source, Func`2 selector)
   at AppStream.DurablePatterns.Executor.StepExecutor.FanOutFanInStep.FanOutFanInStepExecutor.ExecuteFanOutFanInInternalAsync[TInputCollection,TInputItem,TResultCollection,TResultItem](Step step, TaskOrchestrationContext context, TInputCollection input)
   at AppStream.DurablePatterns.Executor.StepExecutor.FanOutFanInStep.FanOutFanInStepExecutor.ExecuteStepInternalAsync(Step step, TaskOrchestrationContext context, Object input)
   at AppStream.DurablePatterns.Executor.DurablePatternsExecutor.ExecuteAsync(IEnumerable`1 steps, TaskOrchestrationContext context).
``` 

There is a call to Linq `Average()` which does not handle empty collections:

https://github.com/Appstream-Studio/durable-patterns/blob/68b5fd8fa53595150ac80ffb6f9ea1e68191e601/src/AppStream.DurablePatterns/Executor/StepExecutor/FanOutFanInStep/FanOutFanInStepExecutor.cs#L108

**Comment by thomaseyde** [comment]
That was fast! Looking forward to it :)

**Comment by thomaseyde** [comment]
Works as a charm :)
